# Generated by Django 3.2 on 2022-12-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='ambulance',
        ),
        migrations.RemoveField(
            model_name='services',
            name='doctorlist',
        ),
        migrations.RemoveField(
            model_name='services',
            name='laboratory',
        ),
        migrations.RemoveField(
            model_name='services',
            name='sergery',
        ),
        migrations.AddField(
            model_name='services',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='services',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
