# Generated by Django 3.2 on 2022-12-24 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_auto_20221224_1241'),
        ('profileapp', '0001_initial'),
        ('contactapp', '0004_auto_20211222_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homeapp.department'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileapp.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='meassage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
