# Generated by Django 3.2 on 2022-12-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0005_auto_20221224_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='department_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
