# Generated by Django 3.2 on 2022-12-24 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0006_auto_20221224_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
    ]
